
---
title: 'Homework #1'
author: "Caitlin Fordell"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This homework is more or less a tutorial that helps you set up the coding environment used in this course, and familiarizes you with the format of the assignment submission. 
As a pre-requisite of this homework, first install R, and then the RStudio (the free version of Rstudio Desktop). 

Please respond to all questions. If the question asks you to do something on your laptop and you have finished that, just say "Done". 

1. Create a folder named `ds202_hw1`, and **either** create an RMarkDown file `hw1.Rmd` under this folder **or** move the provided template into this folder. `hw1.Rmd` will include your solutions. The file and folder names are *case-sensitive*, which means `hw1.Rmd` and `HW1.rmd` are different. *It is crucial to follow the exact folder structure and file names* in this course, so that your homework can be reproduced. The correct folder structure is

    ```
    ds202_hw1
    |-- hw1.Rmd
    |-- hw1.html (generated after knitting)
    ```
    
    Answer: Done (Note that the start of your answer on the next line must be indented. In other words, don't remove the leading spaces.)  
    

2. Write your name in the YAML of your homework `Rmd` file.

    Answer: Done  
    

3. Write a paragraph to introduce yourself. Set your name in bold font and your major in italic. 

    Answer: My name is **Caitlin Fordell** and I am a junior here at Iowa State. I am majoring in *Statistics* and minoring in *General Business and Data Science*. Eventually, I would love to work for a professional football team and perform data analysis on the team or the organization itself.  
  
  
4. Write a paragraph describing a job that you think is related to data science. Include a hyperlink and an image. Make sure your answer is in a nice format to read. 

    Answer: Image of a [Data Scientist](https://www.google.com/search?q=data+scientist+image&rlz=1C1VDKB_enUS929US929&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjh8bL5q7_uAhXEGc0KHS_1CzAQ_AUoAXoECBAQAw&biw=651&bih=601#imgrc=2WQlJDw_JBflaM).  
    I found a job posting for a Data Scientist position at the NSA, which is pretty obviously related to data science given the position name. In that job, the data scientist deals with the collection and processing of international intelligence and correspondence to protect the country. In doing this, they would perform analysis on large amounts of data. The link to the job posting is attached [here](https://apply.intelligencecareers.gov/job-description/1154326).  
    
  
5. What data topic will you be most interested in? (Optional) Provide a source of such dataset if you have.

    Answer: I am most interested in datasets focusing on sports. A lot of sports datasets can be found on [Sports-Statistics.com](https://sports-statistics.com/sports-data/sports-data-sets-for-data-modeling-visualization-predictions-machine-learning/).  
  
  
6. To check that your R and Rstudio installation is correct, find the version of R by entering `version` into the R console. Include this command into a R code trunk in your solution `Rmd` file to have it automatically printed in the knitted html file. 

    Answer: ``` {r}
    version
    ```   
    
  
7. Install git. 
    - If you are on Windows: 
        a. Install [Git for Windows](https://gitforwindows.org/). In the coming weeks we will use the Git Bash (but not the Git GUI). 
        b. After installation, set up Rstudio to use Git bash as the shell for the Terminal: Open RStudio, click Tools--Global Options--Terminal; under **Shells**, select Git Bash; click OK. 
        c. In the main menu of RStudio: click Tools--Terminal--New Terminal. If you have a `$` before your prompt, then you should be good to go.
    - If you are on Linux or macOS, Git has probably been installed by default, so you do not need to install anything. Just click the Terminal tab (above the R Console).

    Answer: Done  
    
  
8. What is the version of your Git? To find out, go to the Terminal tab in RStudio (right to the Console tab), and type in the following command. If it works, this shows that the setup of your terminal and Git is correct. 
<!-- Then explore the bash command line and Git. -->

    ```
    git --version
    ```

    Answer: My version is 2.30.0.windows.2.  
    
  
9. Configure your git username and user email by modifying and entering the following commands into the terminal

    ```
    git config --global user.name "your first and last name"
    git config --global user.email "yourEmail"
    ```

    Answer: Done  
  

10. Register a [GitHub](https://www.github.com) account. What is your username?

    Answer: My username is caitlinfordell.  
    